In [1]:
import torch

In [2]:
normalizers = torch.load('normalize.pth')
in_normalizer = normalizers['in_normalizer']
out_normalizer = normalizers['out_normalizer']

In [4]:
std = in_normalizer.get_std()

tensor([[0.0843, 0.0817, 1.2791, 0.0308, 0.0308, 1.1275],
        [0.0520, 0.0512, 1.2009, 0.0272, 0.0279, 1.0055],
        [0.0229, 0.0227, 1.2413, 0.0260, 0.0261, 0.9713],
        [0.0230, 0.0227, 1.2437, 0.0260, 0.0258, 0.9775],
        [0.0521, 0.0514, 1.2184, 0.0275, 0.0274, 1.0083],
        [0.0836, 0.0809, 1.3215, 0.0308, 0.0308, 1.1443]], device='cuda:0')


In [6]:
std[:6,:3]

tensor([[0.0843, 0.0817, 1.2791],
        [0.0520, 0.0512, 1.2009],
        [0.0229, 0.0227, 1.2413],
        [0.0230, 0.0227, 1.2437],
        [0.0521, 0.0514, 1.2184],
        [0.0836, 0.0809, 1.3215]], device='cuda:0')

In [7]:
std[:6,3:]

tensor([[0.0308, 0.0308, 1.1275],
        [0.0272, 0.0279, 1.0055],
        [0.0260, 0.0261, 0.9713],
        [0.0260, 0.0258, 0.9775],
        [0.0275, 0.0274, 1.0083],
        [0.0308, 0.0308, 1.1443]], device='cuda:0')